/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author abeeh
 */

public class Client_Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Client_Dashboard.class.getName());
    private Freelancer freelancer;
    private Client client;
    /**
     * Creates new form Client_Dashboard
     */
    public Client_Dashboard(Client client) {
        initComponents();
        this.setSize(440, 420);
        this.setLocationRelativeTo(null);
        this.client = client;
        java.awt.Color lightNudeBeige = new java.awt.Color(242, 230, 218);
        this.getContentPane().setBackground(lightNudeBeige);

        java.awt.Color coffeeBrown = new java.awt.Color(54, 43, 36);
        jLabel1.setForeground(coffeeBrown);
        jLabel2.setForeground(coffeeBrown);
        jLabel3.setForeground(coffeeBrown);

        jLabel1.setText("CLIENT DASHBOARD");
        jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 24));
        jLabel1.setForeground(coffeeBrown);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        java.awt.Color btnColor = new java.awt.Color(184, 115, 81);
        java.awt.Color whiteText = java.awt.Color.WHITE;

        javax.swing.JButton[] buttons = {postJob_btn, viewBids_btn, logout_btn, Home_btn, btn_profile, viewJobs_btn};
        for (javax.swing.JButton btn : buttons) {
            btn.setBackground(btnColor);
            btn.setForeground(whiteText);
            btn.setFocusPainted(false);
        }

        this.setLocationRelativeTo(null);
        
        // ── ALIGNMENT FIX ──
        javax.swing.JPanel card = new javax.swing.JPanel(new java.awt.GridBagLayout());
        card.setBackground(new java.awt.Color(242, 230, 218));
        card.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 40, 10, 40));

        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gbc.weightx = 1.0;

        // 1. Create a panel for the two labels to sit side-by-side
        javax.swing.JPanel labelRow = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));
        labelRow.setOpaque(false); // Make transparent so background color shows
        labelRow.add(jLabel2);
        labelRow.add(jLabel3);

        gbc.gridy = 0;
        // 2. Add the label row panel to the main card
        gbc.gridy = 0; gbc.insets = new java.awt.Insets(0, 0, 6, 0);
        card.add(labelRow, gbc);

        // Profile button
        gbc.gridy = 1; gbc.insets = new java.awt.Insets(0, 0, 10, 0);
        btn_profile.setPreferredSize(new java.awt.Dimension(300, 38));
        card.add(btn_profile, gbc);

        // My Bids button
        gbc.gridy = 2; gbc.insets = new java.awt.Insets(0, 0, 10, 0);
        viewBids_btn.setPreferredSize(new java.awt.Dimension(300, 38));
        card.add(viewBids_btn, gbc);

        // View Jobs button
        gbc.gridy = 3; gbc.insets = new java.awt.Insets(0, 0, 10, 0);
        postJob_btn.setPreferredSize(new java.awt.Dimension(300, 38));
        card.add(postJob_btn, gbc);

        // Home button
        gbc.gridy = 4; gbc.insets = new java.awt.Insets(0, 0, 10, 0);
        logout_btn.setPreferredSize(new java.awt.Dimension(300, 38));
        card.add(logout_btn, gbc);

        // Logout button
        gbc.gridy = 5; gbc.insets = new java.awt.Insets(0, 0, 0, 0);
        Home_btn.setPreferredSize(new java.awt.Dimension(300, 38));
        card.add(Home_btn, gbc);

        // Center card on frame
        javax.swing.JPanel outer = new javax.swing.JPanel(new java.awt.GridBagLayout());
        outer.setBackground(new java.awt.Color(242, 230, 218));
        outer.add(card);

        this.getContentPane().setLayout(new java.awt.BorderLayout());
        this.getContentPane().add(outer, java.awt.BorderLayout.CENTER);
        this.setSize(440, 380);
        this.setLocationRelativeTo(null);
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        viewJobs_btn = new javax.swing.JButton();
        profile_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        postJob_btn = new javax.swing.JButton();
        viewBids_btn = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();
        Home_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_profile = new javax.swing.JButton();

        viewJobs_btn.setText("View Jobs");
        viewJobs_btn.addActionListener(this::viewJobs_btnActionPerformed);

        profile_btn.setText("Profile");
        profile_btn.addActionListener(this::profile_btnActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("                CLIENT DASHBOARD");

        postJob_btn.setText("Post Jobs");
        postJob_btn.addActionListener(this::postJob_btnActionPerformed);

        viewBids_btn.setText("View Bids");
        viewBids_btn.addActionListener(this::viewBids_btnActionPerformed);

        logout_btn.setText("Logout");
        logout_btn.addActionListener(this::logout_btnActionPerformed);

        Home_btn.setText("Home");
        Home_btn.addActionListener(this::Home_btnActionPerformed);

        jLabel2.setText("Welcome Client !");

        jLabel3.setText("What would you like to do today ?");

        btn_profile.setText("profile");
        btn_profile.addActionListener(this::btn_profileActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(postJob_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewBids_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logout_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Home_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2)
                        .addGap(93, 93, 93)
                        .addComponent(jLabel3)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btn_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(postJob_btn)
                .addGap(18, 18, 18)
                .addComponent(viewBids_btn)
                .addGap(18, 18, 18)
                .addComponent(logout_btn)
                .addGap(18, 18, 18)
                .addComponent(Home_btn)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {                                           
   
        LoginForm lo = new LoginForm();
        lo.setVisible(true);
        this.dispose();
        
    }                                          

    private void postJob_btnActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        PostJob_Form p = new PostJob_Form(this.client);  

        p.setVisible(true);

        this.dispose();
    }                                           

    private void viewJobs_btnActionPerformed(java.awt.event.ActionEvent evt) {                                             
        ViewJob_Form ViewJob_FormScreen = new ViewJob_Form(this.freelancer);
        ViewJob_FormScreen.setVisible(true);
        this.dispose();
        
    }                                            

    private void viewBids_btnActionPerformed(java.awt.event.ActionEvent evt) {                                             
        clientbidview cb = new clientbidview(client);
        cb.setVisible(true);
        this.dispose();
    }                                            

    private void Home_btnActionPerformed(java.awt.event.ActionEvent evt) {                                         
        home homeScreen = new home();
        homeScreen.setVisible(true);
        this.dispose();
    }                                        

    private void profile_btnActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void btn_profileActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        new profile(client).setVisible(true);
       
        this.dispose();
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton Home_btn;
    private javax.swing.JButton btn_profile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton logout_btn;
    private javax.swing.JButton postJob_btn;
    private javax.swing.JButton profile_btn;
    private javax.swing.JButton viewBids_btn;
    private javax.swing.JButton viewJobs_btn;
    // End of variables declaration                   
}
