/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author A
 */
public class home extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(home.class.getName());

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        try {
            this.getContentPane().setBackground(new java.awt.Color(242, 230, 218));
            
            this.setLocationRelativeTo(null);
            
            heading.setText("WELCOME TO FREELANCE JOB SYSTEM");
            heading.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 24));
            heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            
            heading.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 15));
            heading.setForeground(new java.awt.Color(54, 43, 36));
           
            btn_loginmain.setBackground(new java.awt.Color(184, 115, 81));
            btn_loginmain.setForeground(java.awt.Color.WHITE); 
            btn_loginmain.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
            btn_loginmain.setFocusPainted(false); 
            
            btn_registermain.setBackground(new java.awt.Color(184, 115, 81));
            btn_registermain.setForeground(java.awt.Color.WHITE); 
            btn_registermain.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
            btn_registermain.setFocusPainted(false);

        } catch (Exception e) {
            System.out.println("Styling Error: " + e.getMessage());
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        heading = new javax.swing.JLabel();
        btn_loginmain = new javax.swing.JButton();
        btn_registermain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        heading.setText("                   WELCOME TO FREELANCE JOB SYSTEM");

        btn_loginmain.setText("Login");
        btn_loginmain.addActionListener(this::btn_loginmainActionPerformed);

        btn_registermain.setText("Register");
        btn_registermain.addActionListener(this::btn_registermainActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_loginmain, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154)
                        .addComponent(btn_registermain, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_registermain, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_loginmain, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
        );

        pack();
    }// </editor-fold>                        

    private void btn_loginmainActionPerformed(java.awt.event.ActionEvent evt) {                                              
        LoginForm loginScreen = new LoginForm();
        loginScreen.setVisible(true);
        this.dispose();
    }                                             

    private void btn_registermainActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        RegisterForm registerScreen = new RegisterForm();
        registerScreen.setVisible(true);
        this.dispose();
    }                                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new home().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btn_loginmain;
    private javax.swing.JButton btn_registermain;
    private javax.swing.JLabel heading;
    // End of variables declaration                   
}
